/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// GrafanaListerExpansion allows custom methods to be added to
// GrafanaLister.
type GrafanaListerExpansion interface{}

// GrafanaNamespaceListerExpansion allows custom methods to be added to
// GrafanaNamespaceLister.
type GrafanaNamespaceListerExpansion interface{}

// GrafanaAlertRuleGroupListerExpansion allows custom methods to be added to
// GrafanaAlertRuleGroupLister.
type GrafanaAlertRuleGroupListerExpansion interface{}

// GrafanaAlertRuleGroupNamespaceListerExpansion allows custom methods to be added to
// GrafanaAlertRuleGroupNamespaceLister.
type GrafanaAlertRuleGroupNamespaceListerExpansion interface{}

// GrafanaContactPointListerExpansion allows custom methods to be added to
// GrafanaContactPointLister.
type GrafanaContactPointListerExpansion interface{}

// GrafanaContactPointNamespaceListerExpansion allows custom methods to be added to
// GrafanaContactPointNamespaceLister.
type GrafanaContactPointNamespaceListerExpansion interface{}

// GrafanaDashboardListerExpansion allows custom methods to be added to
// GrafanaDashboardLister.
type GrafanaDashboardListerExpansion interface{}

// GrafanaDashboardNamespaceListerExpansion allows custom methods to be added to
// GrafanaDashboardNamespaceLister.
type GrafanaDashboardNamespaceListerExpansion interface{}

// GrafanaDatasourceListerExpansion allows custom methods to be added to
// GrafanaDatasourceLister.
type GrafanaDatasourceListerExpansion interface{}

// GrafanaDatasourceNamespaceListerExpansion allows custom methods to be added to
// GrafanaDatasourceNamespaceLister.
type GrafanaDatasourceNamespaceListerExpansion interface{}

// GrafanaFolderListerExpansion allows custom methods to be added to
// GrafanaFolderLister.
type GrafanaFolderListerExpansion interface{}

// GrafanaFolderNamespaceListerExpansion allows custom methods to be added to
// GrafanaFolderNamespaceLister.
type GrafanaFolderNamespaceListerExpansion interface{}
