/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/Netcrackerg/qubership-grafana-operator-converter/api/operator/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GrafanaContactPointLister helps list GrafanaContactPoints.
// All objects returned here must be treated as read-only.
type GrafanaContactPointLister interface {
	// List lists all GrafanaContactPoints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.GrafanaContactPoint, err error)
	// GrafanaContactPoints returns an object that can list and get GrafanaContactPoints.
	GrafanaContactPoints(namespace string) GrafanaContactPointNamespaceLister
	GrafanaContactPointListerExpansion
}

// grafanaContactPointLister implements the GrafanaContactPointLister interface.
type grafanaContactPointLister struct {
	indexer cache.Indexer
}

// NewGrafanaContactPointLister returns a new GrafanaContactPointLister.
func NewGrafanaContactPointLister(indexer cache.Indexer) GrafanaContactPointLister {
	return &grafanaContactPointLister{indexer: indexer}
}

// List lists all GrafanaContactPoints in the indexer.
func (s *grafanaContactPointLister) List(selector labels.Selector) (ret []*v1beta1.GrafanaContactPoint, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.GrafanaContactPoint))
	})
	return ret, err
}

// GrafanaContactPoints returns an object that can list and get GrafanaContactPoints.
func (s *grafanaContactPointLister) GrafanaContactPoints(namespace string) GrafanaContactPointNamespaceLister {
	return grafanaContactPointNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GrafanaContactPointNamespaceLister helps list and get GrafanaContactPoints.
// All objects returned here must be treated as read-only.
type GrafanaContactPointNamespaceLister interface {
	// List lists all GrafanaContactPoints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.GrafanaContactPoint, err error)
	// Get retrieves the GrafanaContactPoint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.GrafanaContactPoint, error)
	GrafanaContactPointNamespaceListerExpansion
}

// grafanaContactPointNamespaceLister implements the GrafanaContactPointNamespaceLister
// interface.
type grafanaContactPointNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GrafanaContactPoints in the indexer for a given namespace.
func (s grafanaContactPointNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.GrafanaContactPoint, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.GrafanaContactPoint))
	})
	return ret, err
}

// Get retrieves the GrafanaContactPoint from the indexer for a given namespace and name.
func (s grafanaContactPointNamespaceLister) Get(name string) (*v1beta1.GrafanaContactPoint, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("grafanacontactpoint"), name)
	}
	return obj.(*v1beta1.GrafanaContactPoint), nil
}
