/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/Netcracker/qubership-grafana-operator-converter/api/operator/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GrafanaAlertRuleGroupLister helps list GrafanaAlertRuleGroups.
// All objects returned here must be treated as read-only.
type GrafanaAlertRuleGroupLister interface {
	// List lists all GrafanaAlertRuleGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.GrafanaAlertRuleGroup, err error)
	// GrafanaAlertRuleGroups returns an object that can list and get GrafanaAlertRuleGroups.
	GrafanaAlertRuleGroups(namespace string) GrafanaAlertRuleGroupNamespaceLister
	GrafanaAlertRuleGroupListerExpansion
}

// grafanaAlertRuleGroupLister implements the GrafanaAlertRuleGroupLister interface.
type grafanaAlertRuleGroupLister struct {
	indexer cache.Indexer
}

// NewGrafanaAlertRuleGroupLister returns a new GrafanaAlertRuleGroupLister.
func NewGrafanaAlertRuleGroupLister(indexer cache.Indexer) GrafanaAlertRuleGroupLister {
	return &grafanaAlertRuleGroupLister{indexer: indexer}
}

// List lists all GrafanaAlertRuleGroups in the indexer.
func (s *grafanaAlertRuleGroupLister) List(selector labels.Selector) (ret []*v1beta1.GrafanaAlertRuleGroup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.GrafanaAlertRuleGroup))
	})
	return ret, err
}

// GrafanaAlertRuleGroups returns an object that can list and get GrafanaAlertRuleGroups.
func (s *grafanaAlertRuleGroupLister) GrafanaAlertRuleGroups(namespace string) GrafanaAlertRuleGroupNamespaceLister {
	return grafanaAlertRuleGroupNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GrafanaAlertRuleGroupNamespaceLister helps list and get GrafanaAlertRuleGroups.
// All objects returned here must be treated as read-only.
type GrafanaAlertRuleGroupNamespaceLister interface {
	// List lists all GrafanaAlertRuleGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.GrafanaAlertRuleGroup, err error)
	// Get retrieves the GrafanaAlertRuleGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.GrafanaAlertRuleGroup, error)
	GrafanaAlertRuleGroupNamespaceListerExpansion
}

// grafanaAlertRuleGroupNamespaceLister implements the GrafanaAlertRuleGroupNamespaceLister
// interface.
type grafanaAlertRuleGroupNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GrafanaAlertRuleGroups in the indexer for a given namespace.
func (s grafanaAlertRuleGroupNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.GrafanaAlertRuleGroup, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.GrafanaAlertRuleGroup))
	})
	return ret, err
}

// Get retrieves the GrafanaAlertRuleGroup from the indexer for a given namespace and name.
func (s grafanaAlertRuleGroupNamespaceLister) Get(name string) (*v1beta1.GrafanaAlertRuleGroup, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("grafanaalertrulegroup"), name)
	}
	return obj.(*v1beta1.GrafanaAlertRuleGroup), nil
}
