/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/monitoring/qubership-grafana-operator-converter/api/operator/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GrafanaFolderLister helps list GrafanaFolders.
// All objects returned here must be treated as read-only.
type GrafanaFolderLister interface {
	// List lists all GrafanaFolders in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GrafanaFolder, err error)
	// GrafanaFolders returns an object that can list and get GrafanaFolders.
	GrafanaFolders(namespace string) GrafanaFolderNamespaceLister
	GrafanaFolderListerExpansion
}

// grafanaFolderLister implements the GrafanaFolderLister interface.
type grafanaFolderLister struct {
	indexer cache.Indexer
}

// NewGrafanaFolderLister returns a new GrafanaFolderLister.
func NewGrafanaFolderLister(indexer cache.Indexer) GrafanaFolderLister {
	return &grafanaFolderLister{indexer: indexer}
}

// List lists all GrafanaFolders in the indexer.
func (s *grafanaFolderLister) List(selector labels.Selector) (ret []*v1alpha1.GrafanaFolder, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GrafanaFolder))
	})
	return ret, err
}

// GrafanaFolders returns an object that can list and get GrafanaFolders.
func (s *grafanaFolderLister) GrafanaFolders(namespace string) GrafanaFolderNamespaceLister {
	return grafanaFolderNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GrafanaFolderNamespaceLister helps list and get GrafanaFolders.
// All objects returned here must be treated as read-only.
type GrafanaFolderNamespaceLister interface {
	// List lists all GrafanaFolders in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GrafanaFolder, err error)
	// Get retrieves the GrafanaFolder from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.GrafanaFolder, error)
	GrafanaFolderNamespaceListerExpansion
}

// grafanaFolderNamespaceLister implements the GrafanaFolderNamespaceLister
// interface.
type grafanaFolderNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GrafanaFolders in the indexer for a given namespace.
func (s grafanaFolderNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.GrafanaFolder, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GrafanaFolder))
	})
	return ret, err
}

// Get retrieves the GrafanaFolder from the indexer for a given namespace and name.
func (s grafanaFolderNamespaceLister) Get(name string) (*v1alpha1.GrafanaFolder, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("grafanafolder"), name)
	}
	return obj.(*v1alpha1.GrafanaFolder), nil
}
