/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	versioned "github.com/Netcracker/qubership-grafana-operator-converter/api/client/v1beta1/clientset/versioned"
	internalinterfaces "github.com/Netcracker/qubership-grafana-operator-converter/api/client/v1beta1/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/Netcracker/qubership-grafana-operator-converter/api/client/v1beta1/listers/operator/v1beta1"
	operatorv1beta1 "github.com/Netcracker/qubership-grafana-operator-converter/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GrafanaAlertRuleGroupInformer provides access to a shared informer and lister for
// GrafanaAlertRuleGroups.
type GrafanaAlertRuleGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.GrafanaAlertRuleGroupLister
}

type grafanaAlertRuleGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGrafanaAlertRuleGroupInformer constructs a new informer for GrafanaAlertRuleGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGrafanaAlertRuleGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGrafanaAlertRuleGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGrafanaAlertRuleGroupInformer constructs a new informer for GrafanaAlertRuleGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGrafanaAlertRuleGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GrafanaIntegreatlyV1beta1().GrafanaAlertRuleGroups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GrafanaIntegreatlyV1beta1().GrafanaAlertRuleGroups(namespace).Watch(context.TODO(), options)
			},
		},
		&operatorv1beta1.GrafanaAlertRuleGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *grafanaAlertRuleGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGrafanaAlertRuleGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *grafanaAlertRuleGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operatorv1beta1.GrafanaAlertRuleGroup{}, f.defaultInformer)
}

func (f *grafanaAlertRuleGroupInformer) Lister() v1beta1.GrafanaAlertRuleGroupLister {
	return v1beta1.NewGrafanaAlertRuleGroupLister(f.Informer().GetIndexer())
}
