/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	scheme "github.com/Netcracker/qubership-grafana-operator-converter/api/client/v1beta1/clientset/versioned/scheme"
	v1beta1 "github.com/Netcracker/qubership-grafana-operator-converter/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GrafanaContactPointsGetter has a method to return a GrafanaContactPointInterface.
// A group's client should implement this interface.
type GrafanaContactPointsGetter interface {
	GrafanaContactPoints(namespace string) GrafanaContactPointInterface
}

// GrafanaContactPointInterface has methods to work with GrafanaContactPoint resources.
type GrafanaContactPointInterface interface {
	Create(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.CreateOptions) (*v1beta1.GrafanaContactPoint, error)
	Update(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.UpdateOptions) (*v1beta1.GrafanaContactPoint, error)
	UpdateStatus(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.UpdateOptions) (*v1beta1.GrafanaContactPoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.GrafanaContactPoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.GrafanaContactPointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GrafanaContactPoint, err error)
	GrafanaContactPointExpansion
}

// grafanaContactPoints implements GrafanaContactPointInterface
type grafanaContactPoints struct {
	client rest.Interface
	ns     string
}

// newGrafanaContactPoints returns a GrafanaContactPoints
func newGrafanaContactPoints(c *GrafanaIntegreatlyV1beta1Client, namespace string) *grafanaContactPoints {
	return &grafanaContactPoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the grafanaContactPoint, and returns the corresponding grafanaContactPoint object, and an error if there is any.
func (c *grafanaContactPoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GrafanaContactPoint, err error) {
	result = &v1beta1.GrafanaContactPoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GrafanaContactPoints that match those selectors.
func (c *grafanaContactPoints) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GrafanaContactPointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.GrafanaContactPointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested grafanaContactPoints.
func (c *grafanaContactPoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a grafanaContactPoint and creates it.  Returns the server's representation of the grafanaContactPoint, and an error, if there is any.
func (c *grafanaContactPoints) Create(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.CreateOptions) (result *v1beta1.GrafanaContactPoint, err error) {
	result = &v1beta1.GrafanaContactPoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafanaContactPoint).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a grafanaContactPoint and updates it. Returns the server's representation of the grafanaContactPoint, and an error, if there is any.
func (c *grafanaContactPoints) Update(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.UpdateOptions) (result *v1beta1.GrafanaContactPoint, err error) {
	result = &v1beta1.GrafanaContactPoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		Name(grafanaContactPoint.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafanaContactPoint).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *grafanaContactPoints) UpdateStatus(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.UpdateOptions) (result *v1beta1.GrafanaContactPoint, err error) {
	result = &v1beta1.GrafanaContactPoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		Name(grafanaContactPoint.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafanaContactPoint).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the grafanaContactPoint and deletes it. Returns an error if one occurs.
func (c *grafanaContactPoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *grafanaContactPoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched grafanaContactPoint.
func (c *grafanaContactPoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GrafanaContactPoint, err error) {
	result = &v1beta1.GrafanaContactPoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("grafanacontactpoints").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
