/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"net/http"

	"github.com/Netcracker/qubership-grafana-operator-converter/api/client/v1beta1/clientset/versioned/scheme"
	v1beta1 "github.com/Netcracker/qubership-grafana-operator-converter/api/operator/v1beta1"
	rest "k8s.io/client-go/rest"
)

type GrafanaIntegreatlyV1beta1Interface interface {
	RESTClient() rest.Interface
	GrafanasGetter
	GrafanaAlertRuleGroupsGetter
	GrafanaContactPointsGetter
	GrafanaDashboardsGetter
	GrafanaDatasourcesGetter
	GrafanaFoldersGetter
}

// GrafanaIntegreatly is used to interact with features provided by the grafana.integreatly.org group.
type GrafanaIntegreatlyV1beta1Client struct {
	restClient rest.Interface
}

func (c *GrafanaIntegreatlyV1beta1Client) Grafanas(namespace string) GrafanaInterface {
	return newGrafanas(c, namespace)
}

func (c *GrafanaIntegreatlyV1beta1Client) GrafanaAlertRuleGroups(namespace string) GrafanaAlertRuleGroupInterface {
	return newGrafanaAlertRuleGroups(c, namespace)
}

func (c *GrafanaIntegreatlyV1beta1Client) GrafanaContactPoints(namespace string) GrafanaContactPointInterface {
	return newGrafanaContactPoints(c, namespace)
}

func (c *GrafanaIntegreatlyV1beta1Client) GrafanaDashboards(namespace string) GrafanaDashboardInterface {
	return newGrafanaDashboards(c, namespace)
}

func (c *GrafanaIntegreatlyV1beta1Client) GrafanaDatasources(namespace string) GrafanaDatasourceInterface {
	return newGrafanaDatasources(c, namespace)
}

func (c *GrafanaIntegreatlyV1beta1Client) GrafanaFolders(namespace string) GrafanaFolderInterface {
	return newGrafanaFolders(c, namespace)
}

// NewForConfig creates a new GrafanaIntegreatlyV1beta1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*GrafanaIntegreatlyV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new GrafanaIntegreatlyV1beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*GrafanaIntegreatlyV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &GrafanaIntegreatlyV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new GrafanaIntegreatlyV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *GrafanaIntegreatlyV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new GrafanaIntegreatlyV1beta1Client for the given RESTClient.
func New(c rest.Interface) *GrafanaIntegreatlyV1beta1Client {
	return &GrafanaIntegreatlyV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *GrafanaIntegreatlyV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
