/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/Netcracker/qubership-grafana-operator-converter/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGrafanaContactPoints implements GrafanaContactPointInterface
type FakeGrafanaContactPoints struct {
	Fake *FakeGrafanaIntegreatlyV1beta1
	ns   string
}

var grafanacontactpointsResource = v1beta1.SchemeGroupVersion.WithResource("grafanacontactpoints")

var grafanacontactpointsKind = v1beta1.SchemeGroupVersion.WithKind("GrafanaContactPoint")

// Get takes name of the grafanaContactPoint, and returns the corresponding grafanaContactPoint object, and an error if there is any.
func (c *FakeGrafanaContactPoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GrafanaContactPoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(grafanacontactpointsResource, c.ns, name), &v1beta1.GrafanaContactPoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaContactPoint), err
}

// List takes label and field selectors, and returns the list of GrafanaContactPoints that match those selectors.
func (c *FakeGrafanaContactPoints) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GrafanaContactPointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(grafanacontactpointsResource, grafanacontactpointsKind, c.ns, opts), &v1beta1.GrafanaContactPointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.GrafanaContactPointList{ListMeta: obj.(*v1beta1.GrafanaContactPointList).ListMeta}
	for _, item := range obj.(*v1beta1.GrafanaContactPointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested grafanaContactPoints.
func (c *FakeGrafanaContactPoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(grafanacontactpointsResource, c.ns, opts))

}

// Create takes the representation of a grafanaContactPoint and creates it.  Returns the server's representation of the grafanaContactPoint, and an error, if there is any.
func (c *FakeGrafanaContactPoints) Create(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.CreateOptions) (result *v1beta1.GrafanaContactPoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(grafanacontactpointsResource, c.ns, grafanaContactPoint), &v1beta1.GrafanaContactPoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaContactPoint), err
}

// Update takes the representation of a grafanaContactPoint and updates it. Returns the server's representation of the grafanaContactPoint, and an error, if there is any.
func (c *FakeGrafanaContactPoints) Update(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.UpdateOptions) (result *v1beta1.GrafanaContactPoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(grafanacontactpointsResource, c.ns, grafanaContactPoint), &v1beta1.GrafanaContactPoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaContactPoint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGrafanaContactPoints) UpdateStatus(ctx context.Context, grafanaContactPoint *v1beta1.GrafanaContactPoint, opts v1.UpdateOptions) (*v1beta1.GrafanaContactPoint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(grafanacontactpointsResource, "status", c.ns, grafanaContactPoint), &v1beta1.GrafanaContactPoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaContactPoint), err
}

// Delete takes name of the grafanaContactPoint and deletes it. Returns an error if one occurs.
func (c *FakeGrafanaContactPoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(grafanacontactpointsResource, c.ns, name, opts), &v1beta1.GrafanaContactPoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGrafanaContactPoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(grafanacontactpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.GrafanaContactPointList{})
	return err
}

// Patch applies the patch and returns the patched grafanaContactPoint.
func (c *FakeGrafanaContactPoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GrafanaContactPoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grafanacontactpointsResource, c.ns, name, pt, data, subresources...), &v1beta1.GrafanaContactPoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaContactPoint), err
}
