/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/Netcracker/qubership-grafana-operator-converter/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGrafanaFolders implements GrafanaFolderInterface
type FakeGrafanaFolders struct {
	Fake *FakeObservabilityV1beta1
	ns   string
}

var grafanafoldersResource = v1beta1.SchemeGroupVersion.WithResource("grafanafolders")

var grafanafoldersKind = v1beta1.SchemeGroupVersion.WithKind("GrafanaFolder")

// Get takes name of the grafanaFolder, and returns the corresponding grafanaFolder object, and an error if there is any.
func (c *FakeGrafanaFolders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GrafanaFolder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(grafanafoldersResource, c.ns, name), &v1beta1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaFolder), err
}

// List takes label and field selectors, and returns the list of GrafanaFolders that match those selectors.
func (c *FakeGrafanaFolders) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GrafanaFolderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(grafanafoldersResource, grafanafoldersKind, c.ns, opts), &v1beta1.GrafanaFolderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.GrafanaFolderList{ListMeta: obj.(*v1beta1.GrafanaFolderList).ListMeta}
	for _, item := range obj.(*v1beta1.GrafanaFolderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested grafanaFolders.
func (c *FakeGrafanaFolders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(grafanafoldersResource, c.ns, opts))

}

// Create takes the representation of a grafanaFolder and creates it.  Returns the server's representation of the grafanaFolder, and an error, if there is any.
func (c *FakeGrafanaFolders) Create(ctx context.Context, grafanaFolder *v1beta1.GrafanaFolder, opts v1.CreateOptions) (result *v1beta1.GrafanaFolder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(grafanafoldersResource, c.ns, grafanaFolder), &v1beta1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaFolder), err
}

// Update takes the representation of a grafanaFolder and updates it. Returns the server's representation of the grafanaFolder, and an error, if there is any.
func (c *FakeGrafanaFolders) Update(ctx context.Context, grafanaFolder *v1beta1.GrafanaFolder, opts v1.UpdateOptions) (result *v1beta1.GrafanaFolder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(grafanafoldersResource, c.ns, grafanaFolder), &v1beta1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaFolder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGrafanaFolders) UpdateStatus(ctx context.Context, grafanaFolder *v1beta1.GrafanaFolder, opts v1.UpdateOptions) (*v1beta1.GrafanaFolder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(grafanafoldersResource, "status", c.ns, grafanaFolder), &v1beta1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaFolder), err
}

// Delete takes name of the grafanaFolder and deletes it. Returns an error if one occurs.
func (c *FakeGrafanaFolders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(grafanafoldersResource, c.ns, name, opts), &v1beta1.GrafanaFolder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGrafanaFolders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(grafanafoldersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.GrafanaFolderList{})
	return err
}

// Patch applies the patch and returns the patched grafanaFolder.
func (c *FakeGrafanaFolders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GrafanaFolder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grafanafoldersResource, c.ns, name, pt, data, subresources...), &v1beta1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaFolder), err
}
