/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/Netcracker/qubership-grafana-operator-converter/api/operator/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGrafanaAlertRuleGroups implements GrafanaAlertRuleGroupInterface
type FakeGrafanaAlertRuleGroups struct {
	Fake *FakeGrafanaIntegreatlyV1beta1
	ns   string
}

var grafanaalertrulegroupsResource = v1beta1.SchemeGroupVersion.WithResource("grafanaalertrulegroups")

var grafanaalertrulegroupsKind = v1beta1.SchemeGroupVersion.WithKind("GrafanaAlertRuleGroup")

// Get takes name of the grafanaAlertRuleGroup, and returns the corresponding grafanaAlertRuleGroup object, and an error if there is any.
func (c *FakeGrafanaAlertRuleGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GrafanaAlertRuleGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(grafanaalertrulegroupsResource, c.ns, name), &v1beta1.GrafanaAlertRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaAlertRuleGroup), err
}

// List takes label and field selectors, and returns the list of GrafanaAlertRuleGroups that match those selectors.
func (c *FakeGrafanaAlertRuleGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GrafanaAlertRuleGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(grafanaalertrulegroupsResource, grafanaalertrulegroupsKind, c.ns, opts), &v1beta1.GrafanaAlertRuleGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.GrafanaAlertRuleGroupList{ListMeta: obj.(*v1beta1.GrafanaAlertRuleGroupList).ListMeta}
	for _, item := range obj.(*v1beta1.GrafanaAlertRuleGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested grafanaAlertRuleGroups.
func (c *FakeGrafanaAlertRuleGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(grafanaalertrulegroupsResource, c.ns, opts))

}

// Create takes the representation of a grafanaAlertRuleGroup and creates it.  Returns the server's representation of the grafanaAlertRuleGroup, and an error, if there is any.
func (c *FakeGrafanaAlertRuleGroups) Create(ctx context.Context, grafanaAlertRuleGroup *v1beta1.GrafanaAlertRuleGroup, opts v1.CreateOptions) (result *v1beta1.GrafanaAlertRuleGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(grafanaalertrulegroupsResource, c.ns, grafanaAlertRuleGroup), &v1beta1.GrafanaAlertRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaAlertRuleGroup), err
}

// Update takes the representation of a grafanaAlertRuleGroup and updates it. Returns the server's representation of the grafanaAlertRuleGroup, and an error, if there is any.
func (c *FakeGrafanaAlertRuleGroups) Update(ctx context.Context, grafanaAlertRuleGroup *v1beta1.GrafanaAlertRuleGroup, opts v1.UpdateOptions) (result *v1beta1.GrafanaAlertRuleGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(grafanaalertrulegroupsResource, c.ns, grafanaAlertRuleGroup), &v1beta1.GrafanaAlertRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaAlertRuleGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGrafanaAlertRuleGroups) UpdateStatus(ctx context.Context, grafanaAlertRuleGroup *v1beta1.GrafanaAlertRuleGroup, opts v1.UpdateOptions) (*v1beta1.GrafanaAlertRuleGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(grafanaalertrulegroupsResource, "status", c.ns, grafanaAlertRuleGroup), &v1beta1.GrafanaAlertRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaAlertRuleGroup), err
}

// Delete takes name of the grafanaAlertRuleGroup and deletes it. Returns an error if one occurs.
func (c *FakeGrafanaAlertRuleGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(grafanaalertrulegroupsResource, c.ns, name, opts), &v1beta1.GrafanaAlertRuleGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGrafanaAlertRuleGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(grafanaalertrulegroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.GrafanaAlertRuleGroupList{})
	return err
}

// Patch applies the patch and returns the patched grafanaAlertRuleGroup.
func (c *FakeGrafanaAlertRuleGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GrafanaAlertRuleGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grafanaalertrulegroupsResource, c.ns, name, pt, data, subresources...), &v1beta1.GrafanaAlertRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GrafanaAlertRuleGroup), err
}
