/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/monitoring/qubership-grafana-operator-converter/api/client/v1alpha1/clientset/versioned"
	internalinterfaces "github.com/monitoring/qubership-grafana-operator-converter/api/client/v1alpha1/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/monitoring/qubership-grafana-operator-converter/api/client/v1alpha1/listers/operator/v1alpha1"
	operatorv1alpha1 "github.com/monitoring/qubership-grafana-operator-converter/api/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GrafanaFolderInformer provides access to a shared informer and lister for
// GrafanaFolders.
type GrafanaFolderInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GrafanaFolderLister
}

type grafanaFolderInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGrafanaFolderInformer constructs a new informer for GrafanaFolder type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGrafanaFolderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGrafanaFolderInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGrafanaFolderInformer constructs a new informer for GrafanaFolder type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGrafanaFolderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IntegreatlyV1alpha1().GrafanaFolders(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IntegreatlyV1alpha1().GrafanaFolders(namespace).Watch(context.TODO(), options)
			},
		},
		&operatorv1alpha1.GrafanaFolder{},
		resyncPeriod,
		indexers,
	)
}

func (f *grafanaFolderInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGrafanaFolderInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *grafanaFolderInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operatorv1alpha1.GrafanaFolder{}, f.defaultInformer)
}

func (f *grafanaFolderInformer) Lister() v1alpha1.GrafanaFolderLister {
	return v1alpha1.NewGrafanaFolderLister(f.Informer().GetIndexer())
}
